config/routes.rb
Rails.application.routes.draw do

  root 'rentals#index'
  resources :campsites, only: [:index, :new, :create]
  mount Campingsite::API => '/'
end

app/models/campsite.rb
# == Schema Information
#
# Table name: campsites
#
#  id        :integer          not null, primary key
#  name      :string
#  address   :string
#  city_id   :integer
#  latitude  :float
#  longitude :float
#

class Campsite < ActiveRecord::Base
  belongs_to :city
  geocoded_by :address
  after_validation :geocode 
  # reverse_geocoded_by :latitude, :longitude
  # after_validation :reverse_geocode

  def weather
    zipcode = self.city.yahoo_zipcode
    weather = Weather.lookup(zipcode, Weather::Units::CELSIUS)
    return {
      title: weather.title, 
      temp: "#{weather.condition.temp.to_s} 度",
      condition: weather.condition.text
    }
  end

end

app/models/city.rb
# == Schema Information
#
# Table name: cities
#
#  id            :integer          not null, primary key
#  name          :string
#  yahoo_zipcode :integer
#

class City < ActiveRecord::Base
  has_one :campsite
end

app/models/rental.rb
# == Schema Information
#
# Table name: rentals
#
#  id        :integer          not null, primary key
#  item_name :string
#  price     :integer
#  condition :string
#  available :boolean
#

class Rental < ActiveRecord::Base

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
end

app/controllers/campsites_controller.rb
class CampsitesController < ApplicationController
  def index
    @search = Campsite.search(params[:q])
    @campsites = @search.result.page(params[:page]).per(3)
  end

  def new 
    @campsite = Campsite.new
  end

  def create 
    Campsite.create(strong_params)
    redirect_to campsites_path
  end

  private

  def strong_params
    (params.require(:campsite).permit(:name, :address, :city_id))
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  def index
    @rental_products = Rental.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/campsites/index.html.haml
露營地點

= search_form_for @search do |f| 
  = f.label :name_cont, "Name contains" 
  = f.text_field :name_cont 
  = f.submit "Search" 

= paginate @campsites

%table 
  %thead
    %tr
      %th= t("campsite")
      %th= t("address")
      %th 目前氣溫(攝氏)
      %th 目前天氣
  - @campsites.each do |site|
    %tbody
      %tr
        %td= site.name
        %td= site.address
        %td= site.weather[:temp]
        %td= site.weather[:condition]

=link_to 'New Campsite', new_campsite_path

app/views/campsites/new.html.haml
<h2>推薦一個露營地</h2>

=simple_form_for @campsite do |f|
  = f.input :name, label: '露營地'
  = f.input :address
  = f.association :city, include_blank: false
  = f.button :submit

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoCamping</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rentals/index.html.haml
%h2 Rental Product Index

%table
  %thead
    %tr
      %th 編號
      %th 出租品項
      %th 價錢
      %th 品相
  - @rental_products.each do |item|  
    %tbody
      %tr
        %td= item.id
        %td= item.item_name
        %td= item.price   
        %td= item.condition

= link_to "露營地點", campsites_path 